import React from 'react';

class SearchBar extends React.Component {
	state = {
		term: ''
	};

	/**
	 * @param event default event object generated by the browser
	 * notes: use arrow functions to avoid weird binding issues with this.
	 */
	onFormSubmit= (event) => {
		event.preventDefault();

		// uses props to call to a function defined in the parent component
		this.props.onSubmitFromChildComponent(this.state.term);

	};
	render() {
		return (
			<div className="ui segment">
				<form onSubmit={this.onFormSubmit} className="ui form">
					<div className="field">
						<label>image search</label>
						<input
							type="text"
							value={this.state.term}
							onChange ={event => this.setState({term: event.target.value.toLowerCase()})}
						/>
					</div>
				</form>
			</div>
		)
	}
}

export default SearchBar;